"""
Metrics Parser, Curve Plotter, and Evaluation Reporting Utilities.
==================================================================
Real-Time Industrial Defect Detection System
"""

import os
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from utils.logger import get_logger

logger = get_logger("metrics")


def parse_training_results(results_csv_path: Path) -> pd.DataFrame:
    """
    Parses the training results.csv file generated by Ultralytics YOLOv8.
    """
    if not results_csv_path.exists():
        logger.error(f"Training results CSV not found at: {results_csv_path}")
        raise FileNotFoundError(f"Results CSV not found: {results_csv_path}")
        
    try:
        df = pd.read_csv(results_csv_path)
        df.columns = df.columns.str.strip()
        logger.info(f"Successfully parsed training results CSV. Total epochs: {len(df)}")
        return df
    except Exception as e:
        logger.error(f"Error parsing training results CSV: {e}")
        raise e


def plot_learning_curves(results_csv_path: Path, output_dir: Path):
    """
    Generates training/validation loss curves and mAP metric curves from YOLO results.csv.
    Saves PNG plots to the specified output directory.
    """
    df = parse_training_results(results_csv_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # 1. Plot Loss Curves
    plt.figure(figsize=(10, 6))
    
    # Try to find common YOLO loss column variations
    box_loss_col = [c for c in df.columns if 'train/box_loss' in c]
    val_box_loss_col = [c for c in df.columns if 'val/box_loss' in c]
    cls_loss_col = [c for c in df.columns if 'train/cls_loss' in c]
    val_cls_loss_col = [c for c in df.columns if 'val/cls_loss' in c]
    
    if box_loss_col and val_box_loss_col:
        plt.plot(df['epoch'], df[box_loss_col[0]], label='Train Box Loss', color='blue')
        plt.plot(df['epoch'], df[val_box_loss_col[0]], label='Val Box Loss', color='red', linestyle='--')
        
    if cls_loss_col and val_cls_loss_col:
        plt.plot(df['epoch'], df[cls_loss_col[0]], label='Train Class Loss', color='cyan')
        plt.plot(df['epoch'], df[val_cls_loss_col[0]], label='Val Class Loss', color='magenta', linestyle='--')
        
    plt.title("YOLOv8 Model Training and Validation Loss Curves")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.legend()
    
    loss_plot_path = output_dir / "loss_curves.png"
    plt.savefig(loss_plot_path, dpi=300, bbox_inches='tight')
    plt.close()
    logger.info(f"Saved loss curves plot to: {loss_plot_path}")
    
    # 2. Plot mAP Curves
    plt.figure(figsize=(10, 6))
    map50_col = [c for c in df.columns if 'metrics/mAP50(B)' in c or 'mAP50' in c]
    map95_col = [c for c in df.columns if 'metrics/mAP50-95(B)' in c or 'mAP50-95' in c]
    
    if map50_col:
        plt.plot(df['epoch'], df[map50_col[0]], label='mAP@0.5', color='green', linewidth=2)
    if map95_col:
        plt.plot(df['epoch'], df[map95_col[0]], label='mAP@0.5:0.95', color='orange', linewidth=2)
        
    plt.title("YOLOv8 Model Mean Average Precision (mAP) Curves")
    plt.xlabel("Epoch")
    plt.ylabel("Precision Metric")
    plt.grid(True)
    plt.legend()
    
    map_plot_path = output_dir / "map_curves.png"
    plt.savefig(map_plot_path, dpi=300, bbox_inches='tight')
    plt.close()
    logger.info(f"Saved mAP curves plot to: {map_plot_path}")


def generate_markdown_report(metrics_dict: dict, output_path: Path):
    """
    Saves class-wise and overall object detection metrics into a clean markdown table report.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    lines = [
        "# Model Evaluation Performance Report",
        f"> Generated: {timestamp}",
        "",
        "## Overall Model Metrics",
        "",
        "| Metric | Value |",
        "|---|---|",
    ]
    
    overall = metrics_dict.get("overall", {})
    for k, v in overall.items():
        val = float(v) if (v is not None and not isinstance(v, str)) else 0.0
        lines.append(f"| {k.upper()} | {val:.4f} |")
        
    lines.extend([
        "",
        "## Class-wise Defect Detection Performance",
        "",
        "| Class ID | Class Name | Precision | Recall | mAP@0.5 | mAP@0.5:0.95 |",
        "|---|---|---|---|---|---|",
    ])
    
    classes = metrics_dict.get("classes", {})
    for class_id, data in sorted(classes.items(), key=lambda x: x[0]):
        precision_val = data.get('precision', 0.0)
        recall_val = data.get('recall', 0.0)
        map50_val = data.get('map50', 0.0)
        map95_val = data.get('map95', 0.0)
        
        precision_val = float(precision_val) if (precision_val is not None and not isinstance(precision_val, str)) else 0.0
        recall_val = float(recall_val) if (recall_val is not None and not isinstance(recall_val, str)) else 0.0
        map50_val = float(map50_val) if (map50_val is not None and not isinstance(map50_val, str)) else 0.0
        map95_val = float(map95_val) if (map95_val is not None and not isinstance(map95_val, str)) else 0.0
        
        lines.append(
            f"| {class_id} | {data.get('name', 'N/A')} | "
            f"{precision_val:.4f} | {recall_val:.4f} | "
            f"{map50_val:.4f} | {map95_val:.4f} |"
        )
        
    lines.extend([
        "",
        "---",
        "*Report generated automatically by the Defect Detection System Evaluation Framework.*"
    ])
    
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info(f"Successfully generated markdown evaluation report at: {output_path}")


def generate_splits_comparison_report(val_metrics: dict, test_metrics: dict, output_path: Path):
    """
    Saves a comparative report comparing validation vs test split performance metrics.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    lines = [
        "# Model Splits Performance Comparison Report",
        f"> Generated: {timestamp}",
        "",
        "## Overall Comparative Performance",
        "",
        "| Metric | Validation Split | Test Split | Delta (Test - Val) |",
        "|---|---|---|---|",
    ]
    
    val_overall = val_metrics.get("overall", {})
    test_overall = test_metrics.get("overall", {})
    
    for metric_name in ["precision", "recall", "map50", "map95"]:
        val_val = val_overall.get(metric_name, 0.0)
        test_val = test_overall.get(metric_name, 0.0)
        val_val = float(val_val) if (val_val is not None and not isinstance(val_val, str)) else 0.0
        test_val = float(test_val) if (test_val is not None and not isinstance(test_val, str)) else 0.0
        delta = test_val - val_val
        lines.append(f"| {metric_name.upper()} | {val_val:.4f} | {test_val:.4f} | {delta:+.4f} |")
        
    lines.extend([
        "",
        "## Class-wise Comparative Performance",
        "",
        "| Class ID | Class Name | Val mAP@0.5 | Test mAP@0.5 | Delta mAP@0.5 | Val mAP@0.5:0.95 | Test mAP@0.5:0.95 | Delta mAP@0.5:0.95 |",
        "|---|---|---|---|---|---|---|---|",
    ])
    
    val_classes = val_metrics.get("classes", {})
    test_classes = test_metrics.get("classes", {})
    
    for class_id in sorted(val_classes.keys()):
        val_data = val_classes.get(class_id, {})
        test_data = test_classes.get(class_id, {})
        
        val_map50 = val_data.get("map50", 0.0)
        test_map50 = test_data.get("map50", 0.0)
        val_map50 = float(val_map50) if (val_map50 is not None and not isinstance(val_map50, str)) else 0.0
        test_map50 = float(test_map50) if (test_map50 is not None and not isinstance(test_map50, str)) else 0.0
        delta_map50 = test_map50 - val_map50
        
        val_map95 = val_data.get("map95", 0.0)
        test_map95 = test_data.get("map95", 0.0)
        val_map95 = float(val_map95) if (val_map95 is not None and not isinstance(val_map95, str)) else 0.0
        test_map95 = float(test_map95) if (test_map95 is not None and not isinstance(test_map95, str)) else 0.0
        delta_map95 = test_map95 - val_map95
        
        lines.append(
            f"| {class_id} | {val_data.get('name', 'N/A')} | "
            f"{val_map50:.4f} | {test_map50:.4f} | {delta_map50:+.4f} | "
            f"{val_map95:.4f} | {test_map95:.4f} | {delta_map95:+.4f} |"
        )
        
    lines.extend([
        "",
        "---",
        "*Report generated automatically by the Defect Detection System Evaluation Framework.*"
    ])
    
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info(f"Successfully generated splits comparison report at: {output_path}")
